#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("employeeHelper.Resource", IsApplication=true)]

namespace employeeHelper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int btnCall = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int btnEmployerInfo = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int btnReturn = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int btnSchedule = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int btnUpdate = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int editText1 = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int editText2 = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int imageView1 = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int lblEmployerNameTitle = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int lblPhoneNumberTitle = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int lblTotalPay = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int lblWageLabel = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int lblWeekHours = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int lblWeekTitle = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int myButton = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int txtEmployerName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int txtPhone = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EmployerInfo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Schedule = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int openCamera = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
